# å¿…è¯»ï¼ï¼ï¼
# æ­¤ç‰ˆæœ¬æ²¡æœ‰åšé˜²æ³„éœ²å¤„ç†ï¼Œå¦‚ä»‹æ„è¯·ä½¿ç”¨å¦ä¸€ä¸ªåå­—ä¸ºconfigdnsçš„ç‰ˆæœ¬
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…
proxy-providers:
  Zero:
    url: " "
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿, type: direct}

# å…¨å±€é…ç½® 
mixed-port: 7890
allow-lan: true
bind-address: "*"
# ipv6: false
unified-delay: true
tcp-concurrent: true
# log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# ä¸ºé˜²æ­¢ä½¿ç”¨æ’ä»¶æœ‹å‹é‡åˆ°é¢æ¿é—®é¢˜ï¼Œæˆ‘æ³¨é‡Šæ‰äº†æ­¤æ¨¡å—ã€‚
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: ui
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢ï¼ˆfakeipä¸‹å…¶å®å¯ä»¥ä¸ç”¨å—…æ¢ï¼‰
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #ä½¿ç”¨nikkiï¼Œæ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
  #device: nikki
  #ä½¿ç”¨ä»…å†…æ ¸è‡ªè¡Œä¿®æ”¹ä¸‹é¢ä¸‰é¡¹ä¸ºtrue
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNSæ¨¡å—
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  # ipv6: true
  # respect-rules: true
  enhanced-mode: fake-ip
  # fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - rule-set:fakeipfilter_domain
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - 10.10.0.21
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
 
# å‡ºç«™ç­–ç•¥ï¼Œæ ¹æ®è‡ªå·±æƒ…å†µè°ƒæ•´æ¯ä¸ªç­–ç•¥é‡Œåˆ†ç»„æ’åºï¼Œå¢åˆ éƒ½å¯ä»¥ï¼Œæ¯”å¦‚æŠŠç¾å›½è‡ªåŠ¨æ”¾åˆ°ç¬¬ä¸€ä¸ªï¼Œæ¯”å¦‚åˆ é™¤é¦™æ¸¯æ•…è½¬ï¼Œæ³¨æ„åˆ«æ¼æ‰è¡¨æƒ…é€—å·ç­‰ã€‚
# å¦‚æœç›¸åº”åˆ†ç»„æ²¡æœ‰ç­›é€‰åˆ°å¯¹åº”çš„å›½å®¶ï¼Œè¯·æ ¹æ®è‡ªå·±èŠ‚ç‚¹åå­—è°ƒæ•´ç­›é€‰å…³é”®å­—ã€‚
# æ²¡æœ‰å†ä½¿ç”¨é”šç‚¹ï¼Œæ˜¯è€ƒè™‘å¾ˆå¤šæ–°æ‰‹ä¿®æ”¹éš¾åº¦ï¼Œè¿™æ ·æ–°æ‰‹ä¿®æ”¹æŸä¸ªåˆ†ç»„æ›´å®¹æ˜“äº›ã€‚
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨,ğŸŒ é¦™æ¸¯æ‰‹åŠ¨,ğŸŒ ç¾å›½æ‰‹åŠ¨,ğŸŒ å°æ¹¾æ‰‹åŠ¨, ğŸŒ æ‰‹åŠ¨èŠ‚ç‚¹]}
  - {name: ğŸ¦‰ ZJUå†…ç½‘, type: select, proxies: [ğŸ¯ ç›´è¿]}
  - {name: ğŸ“‘ ZJU Scholar, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ”ï¸ Scholar, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ± GitHub, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: â“‚ï¸ Bing, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ¤– AIæœåŠ¡, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, ğŸŒ å°æ¹¾æ‰‹åŠ¨]}
  - {name: ğŸ“¹ YouTube, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ¥ Netflix, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ¥ AppleTV+, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ¦„ è°·æ­ŒæœåŠ¡, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ è‹¹æœæœåŠ¡, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ’¾ OneDrive, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ® æ¸¸æˆå¹³å°, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ® Steam, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ“² å³æ—¶é€šè®¯, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸ‘¥ ç¤¾äº¤åª’ä½“, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: â¬ PTç«™ç‚¹, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸš€ æµ‹é€Ÿå·¥å…·, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸ¯ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, ğŸŒ æ‰‹åŠ¨èŠ‚ç‚¹]}
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$"}
  - {name: â™»ï¸ ç‹®åŸè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|ç¾)).)*$"}
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å°|TW))^((?!(æ¸¯|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: ğŸŒ é¦™æ¸¯æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸŒ ç¾å›½æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: ğŸŒ å°æ¹¾æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å°|TW))^((?!(æ¸¯|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: ğŸŒ æ‰‹åŠ¨èŠ‚ç‚¹, type: select, include-all: true}
  - {name: ğŸ¯ ç›´è¿, type: select, proxies: [DIRECT]}

# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,private_ip,ğŸ¯ ç›´è¿,no-resolve
  - RULE-SET,private_domain,ğŸ¯ ç›´è¿
  - RULE-SET,ZJU_domain,ğŸ¦‰ ZJUå†…ç½‘
  - RULE-SET,ZJU_scholar,ğŸ“‘ ZJU Scholar
  - RULE-SET,direct_rule,ğŸ¯ ç›´è¿
  - RULE-SET,proxylite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,proxy_rule,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,google_cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,games_cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,steam_download,ğŸ¯ ç›´è¿
  - RULE-SET,games_download_domain,ğŸ¯ ç›´è¿
  - RULE-SET,BT_trackers_domain,ğŸ¯ ç›´è¿
  - RULE-SET,communication_domain,ğŸ“² å³æ—¶é€šè®¯
  - RULE-SET,social-media_domain,ğŸ‘¥ ç¤¾äº¤åª’ä½“
  - RULE-SET,onedrive_domain,ğŸ’¾ OneDrive
  - RULE-SET,bing_domain,â“‚ï¸ Bing
  - RULE-SET,ai_domain,ğŸ¤– AIæœåŠ¡
  - RULE-SET,github_domain,ğŸ± GitHub
  - RULE-SET,speedtest_domain,ğŸš€ æµ‹é€Ÿå·¥å…·
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,apple-tvplus_domain,ğŸ¥ AppleTV+
  - RULE-SET,apple_domain,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,microsoft_domain,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,google_domain,ğŸ¦„ è°·æ­ŒæœåŠ¡
  - RULE-SET,netflix_domain,ğŸ¥ Netflix
  - RULE-SET,steam_domain,ğŸ® Steam
  - RULE-SET,games_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,entertainment_domain,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,pt_domain,â¬ PTç«™ç‚¹
  - RULE-SET,scholar_domain,ğŸ”ï¸ Scholar
  - RULE-SET,gfw_domain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,telegram_ip,ğŸ“² å³æ—¶é€šè®¯,no-resolve
  - RULE-SET,twitter_ip,ğŸ‘¥ ç¤¾äº¤åª’ä½“,no-resolve
  - RULE-SET,facebook_ip,ğŸ‘¥ ç¤¾äº¤åª’ä½“,no-resolve
  - RULE-SET,google_ip,ğŸ¦„ è°·æ­ŒæœåŠ¡,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ Netflix,no-resolve
  - RULE-SET,cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,ZJU_ip,ğŸ¦‰ ZJUå†…ç½‘
  - RULE-SET,cn_ip,ğŸ¯ ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  private_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  ZJU_domain: { <<: *class, url: "https://raw.githubusercontent.com/lugaga11/rule/refs/heads/main/ZJU_Rule/ZJU.list"}
  ZJU_scholar: { <<: *class, url: "https://raw.githubusercontent.com/lugaga11/rule/refs/heads/main/ZJU_Rule/ZJU-Scholar.list"}
  direct_rule: { <<: *class, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  proxy_rule: { <<: *class, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list"}
  google_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-cn.mrs" }
  games_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs" }
  steam_download: { <<: *class, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list"}
  games_download_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-platforms-download.mrs" }
  BT_trackers_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.mrs" }
  communication_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.mrs" }
  social-media_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-!cn.mrs" }
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  bing_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.mrs" }
  ai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-speedtest.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  apple-tvplus_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-tvplus.mrs" }
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs" }
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  steam_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs" }
  games_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs" }
  entertainment_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-entertainment.mrs" }
  pt_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-pt.mrs" }
  scholar_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-!cn.mrs" }
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs" }
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}  
  twitter_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs"}
  facebook_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  ZJU_ip: { <<: *class, url: "https://raw.githubusercontent.com/lugaga11/rule/refs/heads/main/ZJU_Rule/ZJU-IP.list"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}



